site_name: Групповая динамика и коммуникации в программной инженерии
site_url: https://megom2323.github.io/Group-dynamics-HW3/
site_description: Документация проекта по групповой динамике и коммуникациям
repo_url: https://github.com/MegoM2323/Group-dynamics-HW3
repo_name: MegoM2323/Group-dynamics-HW3

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share

nav:
  - Главная: index.md
  - Документация:
    - Процесс работы: contribution.md
    - Настройка GitHub Pages: github-pages-setup.md
  - Контент:
    - Анкета: content/questionnaire.md

plugins:
  - search
