site_name: Групповая динамика и коммуникации в программной инженерии
site_url: https://megom2323.github.io/Group-dynamics-HW3/
site_description: Документация проекта по групповой динамике и коммуникациям
repo_url: https://github.com/MegoM2323/Group-dynamics-HW3
repo_name: MegoM2323/Group-dynamics-HW3

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate

nav:
  - Главная: index.md
  - Рабочие материалы:
    - Анкета с извлечением требований: Анкета с извлечением требований.md
    - Вопросы к интервью: Вопросы к интервью.md
    - Протокол рабочей встречи: Протокол рабочей встречи.md
  - Исходные файлы:
    - Анкета (PDF): content/Анкета_для_извлечения_требований.pdf
    - Ответы заказчика (PDF): content/Ответы на анкету от заказчика.pdf
    - Вопросы к интервью (PDF): content/Вопросы к интервью.pdf

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
