site_name: Групповая динамика и коммуникации в программной инженерии
site_url: https://megom2323.github.io/Group-dynamics-HW3/
site_description: Документация проекта по групповой динамике и коммуникациям в программной инженерии
repo_url: https://github.com/MegoM2323/Group-dynamics-HW3
repo_name: MegoM2323/Group-dynamics-HW3
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Переключить на тёмную тему
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - navigation.path
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - toc.follow
    - toc.integrate

nav:
  - Главная: index.md
  - 📋 Рабочие материалы:
    - Анкета с извлечением требований: Анкета с извлечением требований.md
    - Вопросы к интервью: Вопросы к интервью.md
    - Протокол рабочей встречи: Протокол рабочей встречи.md
    - План коммуникаций: План_коммуникаций_для_проекта_Chrona.md
  - 📁 Исходные файлы:
    - Анкета (PDF): content/Анкета_для_извлечения_требований.pdf
    - Ответы заказчика (PDF): content/Ответы на анкету от заказчика.pdf
    - Вопросы к интервью (PDF): content/Вопросы к интервью.pdf
    - Протокол встречи (PDF): content/Протокол-рабочей-встречи.pdf
    - План коммуникаций (PDF): content/План_коммуникаций_для_проекта_Chrona.pdf

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MegoM2323/Group-dynamics-HW3
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com
  version:
    provider: mike

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
